stages:
  - test
  - build

# Shell executor kullandığınız için 'image' etiketi yoksayılacaktır.
# Go'nun sisteminizde yüklü olduğundan emin olun.

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  CGO_ENABLED: 0
  # DB_HOST IP adresi kullanıcı tarafından güncellendi
  DB_HOST: 172.28.6.165 
  DB_PORT: 5432
  DB_USER: bap
  DB_PASSWORD: bap_admin_1
  DB_NAME: bap_app

cache:
  paths:
    - .go/pkg/mod

before_script:
  - export PATH=$PATH:/usr/local/go/bin
  - mkdir -p .go
  - go mod download

format_check:
  stage: test
  script:
    - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted. Please run 'go fmt ./...'"; gofmt -d .; exit 1; fi

vet:
  stage: test
  script:
    - go vet ./...

unit_tests:
  stage: test
  script:
    - go test -v ./tests/...

build_app:
  stage: build
  script:
    - go build -v -o main ./cmd/server/main.go
  artifacts:
    paths:
      - main
