-- ====================================================
-- DB Admin: Kurulum Bölüm Verileri Göçü (Migration)
-- Üniversite bünyesindeki tüm bölümlerin ve fakülte ilişkilerinin eklenmesi
-- ====================================================

-- 1. Fakülte Tanımlarının Eksiksiz Varlığından Emin Olunması
INSERT INTO fakulte (fakulte_adi, fakulte_kodu, kisa_ad) VALUES
('Eğitim Fakültesi', 'EF', 'Eğitim'),
('Hukuk Fakültesi', 'HF', 'Hukuk'),
('İnsan ve Toplum Bilimleri Fakültesi', 'İTBF', 'İnsan ve Toplum'),
('İslami İlimler Fakültesi', 'İİF', 'İslami İlimler'),
('İşletme ve Yönetim Bilimleri Fakültesi', 'İYBF', 'İşletme'),
('Lisansüstü Eğitim Enstitüsü', 'LEE', 'Lisansüstü'),
('Mühendislik ve Doğa Bilimleri Fakültesi', 'MDBF', 'Mühendislik'),
('Rektörlüğe Bağlı Bölümler', 'RBB', 'Rektörlük'),
('Sağlık Bilimleri Fakültesi', 'SBF', 'Sağlık Bilimleri'),
('Spor Bilimleri Fakültesi', 'SPBF', 'Spor Bilimleri')
ON CONFLICT (fakulte_kodu) DO UPDATE SET fakulte_adi = EXCLUDED.fakulte_adi, kisa_ad = EXCLUDED.kisa_ad;

-- 2. Bölüm Tanımlarının Ekleme Sorguları (bolum tablosu)
INSERT INTO bolum (bolum_adi, bolum_kodu) VALUES
('Arapça Öğretmenliği (%30 Arapça)', 'ARB'),
('İlköğretim Matematik Öğretmenliği', 'IMO'),
('İngilizce Öğretmenliği', 'ELT'),
('Müzik Öğretmenliği', 'MZK'),
('Okul Öncesi Öğretmenliği', 'ECE'),
('Özel Eğitim Öğretmenliği', 'OZE'),
('Rehberlik ve Psikolojik Danışmanlık', 'PDR'),
('Sınıf Öğretmenliği', 'SNE'),
('Türkçe Öğretmenliği', 'TRC'),
('Hukuk', 'HUK'),
('Görsel İletişim Tasarımı', 'GIT'),
('Psikoloji', 'PSK'),
('Psikoloji (İngilizce)', 'PSK-E'),
('Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce)', 'POL'),
('Sosyoloji (%30 İngilizce)', 'SOS'),
('Tarih', 'TAR'),
('Türk Dili ve Edebiyatı', 'TDE'),
('İslami İlimler (%30 Arapça)', 'ISF'),
('İslami İlimler (Arapça)', 'ISF-A'),
('İktisat', 'IKT'),
('İktisat (%30 İngilizce)', 'IKTE'),
('İktisat (İngilizce)', 'IKT-E'),
('İslam İktisadı ve Finans', 'IEF'),
('İslam İktisadı ve Finans (İngilizce)', 'IEF-E'),
('İşletme', 'ISL'),
('İşletme (%30 İngilizce)', 'ISLE'),
('İşletme (İngilizce)', 'ISL-E'),
('Uluslararası Ticaret ve Finansman', 'UTF'),
('Uluslararası Ticaret ve Finansman (İngilizce)', 'UTF-E'),
('Bilgisayar Mühendisliği', 'BIM'),
('Elektrik-Elektronik Mühendisliği (%30 İngilizce)', 'EEM'),
('Endüstri Mühendisliği (%30 İngilizce)', 'END'),
('Gıda Mühendisliği', 'GIM'),
('Gıda Mühendisliği (%30 İngilizce)', 'GIME'),
('İç Mimarlık ve Çevre Tasarımı', 'ICM'),
('Mimarlık', 'MIM'),
('Moleküler Biyoloji ve Genetik (%30 İngilizce)', 'MBG'),
('Yazılım Mühendisliği (%30 İngilizce)', 'YAM'),
('Yazılım Mühendisliği (İngilizce)', 'YAM-E'),
('Beslenme ve Diyetetik', 'BES'),
('Hemşirelik', 'HEM'),
('Sağlık Yönetimi', 'SAY'),
('Sosyal Hizmet', 'SHZ'),
('Beden Eğitimi ve Spor Öğretmenliği', 'BSO'),
('Spor Yöneticiliği', 'SPR'),
('Türk Dili Bölümü', 'TUR'),
('Atatürk İlkeleri ve İnkılap Tarihi Bölümü', 'ATA'),
('İZÜ Seçmeli Dersler', 'IZU'),
('Yabancı Diller Bölümü', 'YDL'),
('Rektörlüğe Bağlı Bölümler', 'KRBB')
ON CONFLICT (bolum_kodu) DO UPDATE SET bolum_adi = EXCLUDED.bolum_adi;

-- 3. Fakülte - Bölüm İlişkilerinin Oluşturulması (fakulte_bolum tablosu)
INSERT INTO fakulte_bolum (fakulte_id, bolum_id)
SELECT f.fakulte_id, b.bolum_id
FROM (
    VALUES
    ('ARB', 'EF'),
    ('IMO', 'EF'),
    ('ELT', 'EF'),
    ('MZK', 'EF'),
    ('ECE', 'EF'),
    ('OZE', 'EF'),
    ('PDR', 'EF'),
    ('SNE', 'EF'),
    ('TRC', 'EF'),
    ('HUK', 'HK'),
    ('HUK', 'HF'),
    ('GIT', 'İTBF'),
    ('GIT', 'ITBF'),
    ('PSK', 'İTBF'),
    ('PSK', 'ITBF'),
    ('PSK-E', 'İTBF'),
    ('PSK-E', 'ITBF'),
    ('POL', 'İTBF'),
    ('POL', 'ITBF'),
    ('SOS', 'İTBF'),
    ('SOS', 'ITBF'),
    ('TAR', 'İTBF'),
    ('TAR', 'ITBF'),
    ('TDE', 'İTBF'),
    ('TDE', 'ITBF'),
    ('ISF', 'İİF'),
    ('ISF', 'IIF'),
    ('ISF-A', 'İİF'),
    ('ISF-A', 'IIF'),
    ('IKT', 'İYBF'),
    ('IKTE', 'İYBF'),
    ('IKT-E', 'İYBF'),
    ('IEF', 'İYBF'),
    ('IEF-E', 'İYBF'),
    ('ISL', 'İYBF'),
    ('ISLE', 'İYBF'),
    ('ISL-E', 'İYBF'),
    ('UTF', 'İYBF'),
    ('UTF-E', 'İYBF'),
    ('BIM', 'MDBF'),
    ('EEM', 'MDBF'),
    ('END', 'MDBF'),
    ('GIM', 'MDBF'),
    ('GIME', 'MDBF'),
    ('ICM', 'MDBF'),
    ('MIM', 'MDBF'),
    ('MBG', 'MDBF'),
    ('YAM', 'MDBF'),
    ('YAM-E', 'MDBF'),
    ('BES', 'SBF'),
    ('HEM', 'SBF'),
    ('SAY', 'SBF'),
    ('SHZ', 'SBF'),
    ('BSO', 'SPBF'),
    ('SPR', 'SPBF'),
    ('TUR', 'RBB'),
    ('ATA', 'RBB'),
    ('IZU', 'RBB'),
    ('YDL', 'RBB'),
    ('KRBB', 'RBB')
) AS mapping(bolum_kodu, fakulte_kodu)
JOIN bolum b ON b.bolum_kodu = mapping.bolum_kodu
JOIN fakulte f ON f.fakulte_kodu = mapping.fakulte_kodu
ON CONFLICT (fakulte_id, bolum_id) DO NOTHING;
